In [5]:
import numpy as np

In [6]:
N = 1000
A = np.array([
        [10.0, -1.0, 2.0, 0.0],
        [-1.0, 11.0, -1.0, 3.0],
        [2.0, -1.0, 10.0, -1.0],
        [0.0, 3.0, -1.0, 8.0],
    ])
b = np.array([6.0, 25.0, -11.0, 15.0])

for i, row in enumerate(A): 
    s = " + ".join([f"{e} x{i}" for i, e in enumerate(row)]) + " = " +  str(b[i])
    print(s.replace("+ -", "- "))

10.0 x0 - 1.0 x1 + 2.0 x2 + 0.0 x3 = 6.0
-1.0 x0 + 11.0 x1 - 1.0 x2 + 3.0 x3 = 25.0
2.0 x0 - 1.0 x1 + 10.0 x2 - 1.0 x3 = -11.0
0.0 x0 + 3.0 x1 - 1.0 x2 + 8.0 x3 = 15.0


In [27]:
# gauss jacobi
x = np.zeros_like(b)
for it_count in range(N):
    x_new = np.zeros_like(x)
    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x[:i])
        s2 = np.dot(A[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if x_new[i] == x_new[i-1]: break
    if np.allclose(x, x_new, atol=1e-10, rtol=0.): break
    x = x_new

In [28]:
# gauss seidel
x = np.zeros_like(b, np.float_)
for it_count in range(1, N):
    x_new = np.zeros_like(x, dtype=np.float_)
    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x_new[:i])
        s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
        x_
        new[i] = (b[i] - s1 - s2) / A[i, i]
    if np.allclose(x, x_new, rtol=1e-8): break
    x = x_new

In [29]:
for row in x: print(x)

[ 1.  2. -1.  1.]
[ 1.  2. -1.  1.]
[ 1.  2. -1.  1.]
[ 1.  2. -1.  1.]
